feat: [UEPR-15] Updated script to fix build issues and refactored logic for merging branches
scratchfoundation/scratch-editor pull request #2
Opened 2024-07-08 10:29 UTC by MiroslavDionisiev

### Jira Ticket
[UEPR-15](https://scratchfoundation.atlassian.net/browse/UEPR-15)

### Proposed Changes
Changed the logic for creating monorepo branches and merging code. Added logic that fixes wrong paths after the merge in the monorepo and ensures everything builds properly.

[UEPR-15]: https://scratchfoundation.atlassian.net/browse/UEPR-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-09 07:38 UTC, sashodada approved these changes

2024-07-09 07:38 UTC, sashodada commented on scripts/build-monorepo.sh
>      scratch-vm \
Even though they are tracked externally, should we leave the removed repos in a comment somewhere around here for future reference? There is a commented out definition of `ALL_REPOS` below we could probably reuse. Maybe also changing the comment above the `ALL_REPOS` definition to fit the current state of the script would be helpful as well

2024-07-09 07:38 UTC, sashodada commented on scripts/build-monorepo.sh
> +    if [ -z "$(git -C "${BUILD_TMP}/${REPO_NAME}" branch --list "$BRANCH")" ]; then
Can this conditional be skipped since the first check is against an empty branch name?

2024-07-09 07:38 UTC, sashodada commented on scripts/build-monorepo.sh
> +                jq  "del(.peerDependencies.\"$DEP\")" "${BUILD_OUT}/workspaces/${REPO}/package.json"  | sponge "${BUILD_OUT}/workspaces/${REPO}/package.json"
Are the duplications in these statements worth extracting in a variable?

2024-07-16 17:55 UTC, cwillisf reviewed
Looking good! I have some questions about potential simplification, but if there's a reason to keep it the way it is then I think that's fine :)

2024-07-16 17:55 UTC, cwillisf commented on scripts/build-monorepo.sh
> +    clone_repository $REPO_NAME
Is there a way to skip this clone step, since we will already have cloned the repo in `add_repo_to_monorepo`? Or is there a reason it needs to be cloned again?

I'm wondering if `add_gh_pages` could instead be a special branch handler in the `DEST_BRANCH` loop in `add_repo_to_monorepo`. Maybe something like:
```sh
gh-pages)
  add_gh_pages $REPO_NAME
  continue
  ;;
```

2024-07-16 17:55 UTC, cwillisf commented on scripts/build-monorepo.sh
> +    clone_repository $REPO_NAME
...or possibly even just an "if the branch is `gh-pages` then create it a little bit differently" clause in the `create the destination branch if it doesn't exist` section of `add_repo_to_monorepo`?

2024-07-16 17:55 UTC, cwillisf commented on scripts/build-monorepo.sh
> +    else
Is this different only because a new `gh-pages` branch shouldn't contain the source code (and other contents) from `develop`? Or is there more going on here?

2024-07-17 13:12 UTC, MiroslavDionisiev commented on scripts/build-monorepo.sh
> +    clone_repository $REPO_NAME
The reason is that after we changed once the root to be treated as directory with `--to-subdirectory-filter` the rerun of the command with different values keeps the structure created by the first call. This may have a better solution but I decided to not try and over-engineer it.

2024-07-17 13:12 UTC, MiroslavDionisiev commented on scripts/build-monorepo.sh
> +    else
My intention was to create an orphan branch so that its history is not associated with the branch it is checked out of. However I didn't like the state of the branch after `git checkout --orphan` and decided to go with this solution.

2024-08-08 15:36 UTC, cwillisf requested changes

2024-08-08 15:36 UTC, cwillisf commented on scripts/build-monorepo.sh
> +    nvm use < .nvmrc
I don't think `nvm` uses `stdin` at all, so I believe these redirects are unnecessary. As long as `.nvmrc` is present in the current working directory, this should work the same:
```suggestion
    nvm install
    nvm use
```

2024-08-08 15:36 UTC, cwillisf commented on scripts/git-batch-push.sh
> +    git -C "$BUILD_OUT" push $REMOTE HEAD:refs/heads/$BRANCH --force
Is `--force` necessary? It makes me nervous about the possibility of something going wrong and causing this to force-push to the wrong branch or repo :sweat_smile:

If possible, I'd prefer to remove `--force` here and instead require a human to prepare the remote branch, maybe with a manual force-push to a base commit.

2024-08-09 08:35 UTC, MiroslavDionisiev commented on scripts/git-batch-push.sh
> +    git -C "$BUILD_OUT" push $REMOTE HEAD:refs/heads/$BRANCH --force
Yeah, my idea was this value to be replaced with where the fork of the one running the script is, however I didn't make it obvious.

2024-08-09 14:05 UTC, cwillisf approved these changes

2024-08-12 06:46 UTC, merged