Feature/uepr 65 confirmation prompt when deleting
scratchfoundation/scratch-editor pull request #29
Opened 2024-10-02 15:41 UTC by KManolov3

### Resolves

https://scratchfoundation.atlassian.net/browse/UEPR-65

### Proposed Changes

Adds a prompt modal when attempting to delete an asset. 

![image](https://github.com/user-attachments/assets/21dd9c19-18a6-4399-b6d1-3ec2cf24e480)

### Reason for Changes

### Test Coverage

Updated corresponding unit and integration tests
Added a new unit test for the cases that include a confirmation modal

2024-10-02 22:45 UTC, cwillisf requested changes
The code looks good to me, but this has made me realize that we didn't include a UX design with this ticket. Sorry about that! We should talk to Tif about the design for this dialog.

2024-10-02 22:45 UTC, cwillisf commented on packages/scratch-gui/test/unit/containers/sprite-selector-item.test.jsx
> +        }});
Thanks for making the test work even though you had to jump through extra hoops!

2024-10-09 08:05 UTC, MiroslavDionisiev commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +        isOpen
From where do we get `isOpen`?

2024-10-09 08:05 UTC, MiroslavDionisiev commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +            { modalPosition === 'right' ?
We can avoid using the ternary operator in this case.

2024-10-09 08:05 UTC, MiroslavDionisiev commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +            {modalPosition === 'left' ?
ditto

2024-10-09 08:05 UTC, MiroslavDionisiev commented on packages/scratch-gui/src/containers/sprite-selector-item.jsx
> +            {this.state.isDeletePromptOpen ? <DeleteConfirmationPrompt
ditto

2024-10-09 08:07 UTC, MiroslavDionisiev commented
The text colour of the buttons seems black

2024-10-09 08:22 UTC, KManolov3 commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +        isOpen
This prop means it's always open (when rendered). We practically create a new instance of the modal component each time we want to show it, with different data. Chose to implement it this way to be consistent with other modals throughout the app.

2024-10-09 08:24 UTC, KManolov3 commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +            { modalPosition === 'right' ?
What do you propose instead of a ternary?

2024-10-09 08:26 UTC, KManolov3 commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +            { modalPosition === 'right' ?
{cond && <Component />} syntax?

2024-10-09 08:48 UTC, MiroslavDionisiev commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +            { modalPosition === 'right' ?
Yeah we can do `condition && component`. That was my intention, forgot to write it down, sorry

2024-10-09 09:50 UTC, KManolov3 commented on packages/scratch-gui/src/components/delete-confirmation-prompt/delete-confirmation-prompt.jsx
> +            { modalPosition === 'right' ?
You are correct, as long as `condition` is a boolean. If it is something else that evaluates to another truthy value - string, number -> React will render it and cause unexpected behaviour/error. Since it's easy to make such a change (e.g. refactor `myNum > 0 &&` to just `myNum &&`) without noticing, I prefer to consistently use ternaries with `null` in the else case.

2024-10-09 14:22 UTC, MiroslavDionisiev approved these changes

2024-10-10 11:45 UTC, merged